version: "3"

tasks:
  install:
    deps:
      - yarn-install
      - composer-install

  yarn-install:
    cmd: yarn install

  composer-install:
    cmd: composer install

  composer-install-prod:
    cmd: composer install --optimize-autoloader --no-dev

  serve:
    cmd: npm run server

  browser-sync:
    cmd: npm run browser-sync

  vite-assets:
    cmd: npm run vite:assets

  dev:
    deps:
      - serve
      - browser-sync
      - vite-assets
    env:
      DEV_MODE: true

  yarn-prod:
    cmds:
      - yarn install
      - yarn prod

  static-build:
    deps:
      - yarn-prod
    cmds:
      - docker build -t static-app -f static-build.Dockerfile .
      - docker cp $(docker create --name static-app-tmp static-app):/go/src/app/dist/frankenphp-linux-x86_64 .static-builds/rehoboth-linux-x86_64
      - docker rm static-app-tmp
